import type { ContractAnalysis } from "@/lib/types";

/**
 * Plain-text export of an analysis for download (no HTML).
 */
export function buildAnalysisReportText(
  fileName: string,
  analysis: ContractAnalysis,
  options?: { demoMode?: boolean }
): string {
  const lines: string[] = [];

  lines.push("ClearContract — Contract audit report");
  lines.push("=".repeat(44));
  lines.push("");
  lines.push(`File: ${fileName}`);
  lines.push(`Generated: ${new Date().toLocaleString()}`);
  if (options?.demoMode) {
    lines.push("Report type: Demo / sample analysis");
  }
  lines.push("");
  lines.push("IMPORTANT — NOT LEGAL ADVICE");
  lines.push("-".repeat(32));
  lines.push(
    "This report is generated by AI for general informational purposes only. It is not legal advice, does not create an attorney-client relationship, and may contain errors. Laws vary by jurisdiction. For decisions about signing, negotiating, or enforcing a contract, consult a qualified attorney licensed in your area."
  );
  lines.push("");

  lines.push("OVERALL SUMMARY");
  lines.push("-".repeat(18));
  lines.push(analysis.overallSummary || "(None)");
  lines.push("");

  const hf = analysis.hiddenFees;
  lines.push("HIDDEN COSTS");
  lines.push("-".repeat(14));
  if (hf?.found && hf.items?.length) {
    hf.items.forEach((item, i) => {
      lines.push(`  ${i + 1}. [${item.riskLevel.toUpperCase()}] ${item.description}`);
      if (item.location) lines.push(`     Location: ${item.location}`);
      if (item.amount) lines.push(`     Amount: ${item.amount}`);
      lines.push("");
    });
    lines.push(`Summary: ${hf.summary}`);
  } else {
    lines.push("No significant hidden costs identified.");
  }
  lines.push("");

  const tc = analysis.terminationClauses;
  lines.push("TERMINATION CLAUSES");
  lines.push("-".repeat(22));
  if (tc?.found && tc.items?.length) {
    tc.items.forEach((item, i) => {
      lines.push(`  ${i + 1}. [${item.riskLevel.toUpperCase()}] ${item.type}`);
      lines.push(`     ${item.description}`);
      if (item.noticePeriod) lines.push(`     Notice: ${item.noticePeriod}`);
      if (item.penalties) lines.push(`     Penalties: ${item.penalties}`);
      lines.push("");
    });
    lines.push(`Summary: ${tc.summary}`);
  } else {
    lines.push("No concerning termination language identified.");
  }
  lines.push("");

  const lr = analysis.liabilityRisks;
  lines.push("LIABILITY RISKS");
  lines.push("-".repeat(17));
  if (lr?.found && lr.items?.length) {
    lr.items.forEach((item, i) => {
      lines.push(`  ${i + 1}. [${item.riskLevel.toUpperCase()}] ${item.clause}`);
      lines.push(`     ${item.description}`);
      lines.push(`     Impact: ${item.impact}`);
      lines.push("");
    });
    lines.push(`Summary: ${lr.summary}`);
  } else {
    lines.push("No major liability risks detected.");
  }
  lines.push("");

  const glossary = analysis.jargonGlossary;
  if (glossary?.length) {
    lines.push("JARGON GLOSSARY");
    lines.push("-".repeat(16));
    glossary.forEach((e) => {
      lines.push(`• ${e.term}: ${e.definition}`);
    });
    lines.push("");
  }

  lines.push("— End of report —");
  return lines.join("\n");
}

export function analysisReportFilename(fileName: string): string {
  const base = fileName
    .replace(/\.[^/.]+$/, "")
    .replace(/[^a-zA-Z0-9._-]+/g, "_")
    .slice(0, 80);
  return `clearcontract-audit-${base || "contract"}.txt`;
}
